project_id = "xbywiwobovzxybzsubhs"

[functions.parse-recipe]
verify_jwt = false

[functions.recipe-assistant]
verify_jwt = false

[functions.import-recipe-url]
verify_jwt = false

[functions.parse-video-text]
verify_jwt = false

[functions.app-guide]
verify_jwt = false
